from enum import Enum

class NWMConfiguration(Enum):
    ANALYSIS_ASSIM = "analysis_assim"
    ANALYSIS_ASSIM_ALASKA = "analysis_assim_alaska"
    ANALYSIS_ASSIM_ALASKA_NO_DA = "analysis_assim_alaska_no_da"
    ANALYSIS_ASSIM_COASTAL_ATLGULF = "analysis_assim_coastal_atlgulf"
    ANALYSIS_ASSIM_COASTAL_HAWAII = "analysis_assim_coastal_hawaii"
    ANALYSIS_ASSIM_COASTAL_PACIFIC = "analysis_assim_coastal_pacific"
    ANALYSIS_ASSIM_COASTAL_PUERTORICO = "analysis_assim_coastal_puertorico"
    ANALYSIS_ASSIM_EXTEND = "analysis_assim_extend"
    ANALYSIS_ASSIM_EXTEND_ALASKA = "analysis_assim_extend_alaska"
    ANALYSIS_ASSIM_EXTEND_ALASKA_NO_DA = "analysis_assim_extend_alaska_no_da"
    ANALYSIS_ASSIM_EXTEND_COASTAL_ATLGULF = "analysis_assim_extend_coastal_atlgulf"
    ANALYSIS_ASSIM_EXTEND_COASTAL_PACIFIC = "analysis_assim_extend_coastal_pacific"
    ANALYSIS_ASSIM_EXTEND_NO_DA = "analysis_assim_extend_no_da"
    ANALYSIS_ASSIM_HAWAII = "analysis_assim_hawaii"
    ANALYSIS_ASSIM_HAWAII_NO_DA = "analysis_assim_hawaii_no_da"
    ANALYSIS_ASSIM_LONG = "analysis_assim_long"
    ANALYSIS_ASSIM_LONG_NO_DA = "analysis_assim_long_no_da"
    ANALYSIS_ASSIM_NO_DA = "analysis_assim_no_da"
    ANALYSIS_ASSIM_PUERTORICO = "analysis_assim_puertorico"
    ANALYSIS_ASSIM_PUERTORICO_NO_DA = "analysis_assim_puertorico_no_da"
    FORCING_ANALYSIS_ASSIM = "forcing_analysis_assim"
    FORCING_ANALYSIS_ASSIM_ALASKA = "forcing_analysis_assim_alaska"
    FORCING_ANALYSIS_ASSIM_EXTEND = "forcing_analysis_assim_extend"
    FORCING_ANALYSIS_ASSIM_EXTEND_ALASKA = "forcing_analysis_assim_extend_alaska"
    FORCING_ANALYSIS_ASSIM_HAWAII = "forcing_analysis_assim_hawaii"
    FORCING_ANALYSIS_ASSIM_PUERTORICO = "forcing_analysis_assim_puertorico"
    FORCING_MEDIUM_RANGE = "forcing_medium_range"
    FORCING_MEDIUM_RANGE_ALASKA = "forcing_medium_range_alaska"
    FORCING_MEDIUM_RANGE_BLEND = "forcing_medium_range_blend"
    FORCING_MEDIUM_RANGE_BLEND_ALASKA = "forcing_medium_range_blend_alaska"
    FORCING_SHORT_RANGE = "forcing_short_range"
    FORCING_SHORT_RANGE_ALASKA = "forcing_short_range_alaska"
    FORCING_SHORT_RANGE_HAWAII = "forcing_short_range_hawaii"
    FORCING_SHORT_RANGE_PUERTORICO = "forcing_short_range_puertorico"
    LONG_RANGE_MEM1 = "long_range_mem1"
    LONG_RANGE_MEM2 = "long_range_mem2"
    LONG_RANGE_MEM3 = "long_range_mem3"
    LONG_RANGE_MEM4 = "long_range_mem4"
    MEDIUM_RANGE_ALASKA_MEM1 = "medium_range_alaska_mem1"
    MEDIUM_RANGE_ALASKA_MEM2 = "medium_range_alaska_mem2"
    MEDIUM_RANGE_ALASKA_MEM3 = "medium_range_alaska_mem3"
    MEDIUM_RANGE_ALASKA_MEM4 = "medium_range_alaska_mem4"
    MEDIUM_RANGE_ALASKA_MEM5 = "medium_range_alaska_mem5"
    MEDIUM_RANGE_ALASKA_MEM6 = "medium_range_alaska_mem6"
    MEDIUM_RANGE_ALASKA_NO_DA = "medium_range_alaska_no_da"
    MEDIUM_RANGE_BLEND = "medium_range_blend"
    MEDIUM_RANGE_BLEND_ALASKA = "medium_range_blend_alaska"
    MEDIUM_RANGE_BLEND_COASTAL_ATLGULF = "medium_range_blend_coastal_atlgulf"
    MEDIUM_RANGE_BLEND_COASTAL_PACIFIC = "medium_range_blend_coastal_pacific"
    MEDIUM_RANGE_COASTAL_ATLGULF_MEM1 = "medium_range_coastal_atlgulf_mem1"
    MEDIUM_RANGE_COASTAL_PACIFIC_MEM1 = "medium_range_coastal_pacific_mem1"
    MEDIUM_RANGE_MEM1 = "medium_range_mem1"
    MEDIUM_RANGE_MEM2 = "medium_range_mem2"
    MEDIUM_RANGE_MEM3 = "medium_range_mem3"
    MEDIUM_RANGE_MEM4 = "medium_range_mem4"
    MEDIUM_RANGE_MEM5 = "medium_range_mem5"
    MEDIUM_RANGE_MEM6 = "medium_range_mem6"
    MEDIUM_RANGE_NO_DA = "medium_range_no_da"
    SHORT_RANGE = "short_range"
    SHORT_RANGE_ALASKA = "short_range_alaska"
    SHORT_RANGE_COASTAL_ATLGULF = "short_range_coastal_atlgulf"
    SHORT_RANGE_COASTAL_HAWAII = "short_range_coastal_hawaii"
    SHORT_RANGE_COASTAL_PACIFIC = "short_range_coastal_pacific"
    SHORT_RANGE_COASTAL_PUERTORICO = "short_range_coastal_puertorico"
    SHORT_RANGE_HAWAII = "short_range_hawaii"
    SHORT_RANGE_HAWAII_NO_DA = "short_range_hawaii_no_da"
    SHORT_RANGE_PUERTORICO = "short_range_puertorico"
    SHORT_RANGE_PUERTORICO_NO_DA = "short_range_puertorico_no_da"
    USGS_TIMESLICES = "usgs_timeslices"
    
def validate_configuration(config: str) -> bool:
    try:
        NWMConfiguration(config)
        return True
    except ValueError:
        return False
